#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
rm log.*
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=$(getApplication)

runApplication blockMesh
runApplication topoSet
runApplication createPatch -overwrite
##runApplication $application

#------------------------------------------------------------------------------
